config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'

  devise_for :admins, path: "admin", 
    controllers: { sessions: "admin/sessions", registrations: 'admin/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
  end
  
  devise_for :teachers, path: "teachers", 
    controllers: { sessions: "teachers/sessions", registrations: 'teachers/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
  end
  
  scope :admin do
    resources :tips
    get      'teachers'                        , to: 'admin/teachers#index', as: :admin_teachers_index
    get      'teachers/new'                    , to: 'admin/teachers#new', as: :admin_teachers_new
    post     'teachers'                        , to: 'admin/teachers#create', as: :admin_teachers_create
    
    #resources :teachers, :controller => "admin/teachers"
  end
  resources :teachers do
    resources :lessons
  end
  
  patch 'teachers/avatarupload' => 'teachers#avatarupload', as: :teacher_avatar_upload
  
  get 'invalid' => 'landing#invalid', as: :invalid
  get 'mailtest' => 'landing#mailtest', as: :mailtest
  
  get 'settings' => 'teachers#settings', as: :settings

  post 'save_settings' => 'teachers#save_settings', as: :save_settings

  devise_for :users
  resources :users

  namespace :api, constraints: { format: 'json' } do  
    devise_for :users, controllers: {sessions: "api/sessions", registrations: "api/registrations", passowords: "api/passwords"}

    resources :tips, only: [:index]

    post 'users/:id/lessons/remove_reserves.json' => 'reserves#removemany', as: :removereserves

    get     'order/:order_id/verify'                        , to: 'orders#verify', as: :orders_verify
    post    ':user_id/mailtest'                             , to: 'orders#mailtest'
    post    'order/:order_id/pay'                           , to: 'orders#pay',            as: :pay
    get     'confirmation'                                  , to: 'orders#confirmation',   as: :confirmation
    post    'notify'                                        , to: 'orders#notify',   as: :pay_notify

    post    'avatar_upload'                                 , to: 'users#avatar_upload'
    post    'order'                                         , to: 'orders#create'
    
    resources :users do
      get '' => 'users#index', as: :user_index
      get 'reserves' => 'reserves#index', as: :reserves_index
      # /api/users/:user_id/lessons/:lesson_id/reserves
      resources :lessons do
        resources :reserves
      end
      member do  
        get '' => 'users#show', as: :user 
        put 'edit' => 'users#edit', as: :user_edit
      end
    end
    
    post 'users/:id/lessons/reserves.json' => 'reserves#createmany', as: :createreserves
    
    post 'reservelessons/rate' => 'reserves#rate', as: :reserves_rate

    get 'teachers/:id/lessons' => 'lessons#index', as: :teachers_lesson
    get 'teachers/:id' => 'teachers#show', as: :teacher
    get 'teachers' => 'teachers#index', as: :teacher_index
    # get 'search' => 'lessons#search', as: :lesson_search
    
    get 'languages' => 'lists#languages', as: :languages_list
    get 'levels' => 'lists#levels', as: :levels_list
    get 'schedules' => 'lists#schedules', as: :schedules_list
    get 'platforms' => 'lists#platforms', as: :platforms_list
    get 'search' => 'teachers#search', as: :teacher_search

    # get  'reserves' => 'users#index', as: :reserve_index
    # get  'reserves/:id' => 'users#show', as: :reserve
    # post 'reserves' => 'users#new', as: :reserve_new
    
  end
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<ul class="list-inline">
					<a href="#about">
					<h8>
						Sobre
					</h8></a>
					</li>
					<li class="footer-menu-divider">
						&sdot;
					</li>
					<li>
						<a href="#contact">
						<h8>
							Contato
						</h8></a>
					</li>
					<li class="area_professor">
						<%= link_to 'Área do Professor', new_teacher_session_path %>
					</li>
					<li class="footer-menu-divider">
						&sdot;
					</li>
					<p class="copyright text-muted small one">
						<a href="https://www.facebook.com/ProfessoresWee"> <img src="/assets/square-facebook-512.png"> </a> Copyright &copy; 2015 <a href="http://doisdoissete.com">
						<h9>
							doisdoissete.
						</h9></a> All Rights Reserved
					</p>
				</ul>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_footer2.html.erb
    <!-- Footer -->
    <footer id="footer2">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">                      
                    <p class="copyright text-muted small one">
						<a href="https://www.facebook.com/ProfessoresWee"> <img src="/assets/square-facebook-512.png"> </a> Copyright &copy; 2015 <a href="http://doisdoissete.com">
						<h9>
							doisdoissete.
						</h9></a> All Rights Reserved
					</p>
                    </ul>
                </div>
            </div>
        </div> 
    </footer>

app/views/shared/_menuitens.html.erb
<%= nav_link 'Editar Perfil', edit_teacher_registration_path %> 
<%= nav_link 'Meus Horários', teacher_lessons_path(current_teacher) %>
<%= nav_link 'Meus Idiomas', settings_path %> 
<%= nav_link "[#{current_teacher.name}] Sair", destroy_teacher_session_path, :delete %>
<%if not current_teacher.avatar.nil? %>
	<li>
	<%= image_tag current_teacher.avatar.url, class: "avatar-header-size" %>
	</li>
<%end%>

app/views/shared/_menuitens_admin.html.erb
<%= nav_link 'Dicas', tips_path %> 
<%= nav_link 'Professores', admin_teachers_index_path %> 
<%= nav_link "[#{current_admin.email}] Sair", destroy_admin_session_path, :delete %>

app/views/shared/_navigation_bar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
	<div class="container topnav">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand topnav" href="http://www.weeapp.com.br">
			<h8><img src="/assets/footer.png" alt="Logo">Wee App
			</h8></a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if defined? locals and locals[:home_menu] %>
				<li>
					<a href="#about">
					<h8>
						Sobre
					</h8></a>
				</li>
				<li>
					<a href="#contact">
					<h8>
						Contato
					</h8></a>
				</li>
				<% end %>

				<% if teacher_signed_in? %>
				<%= render 'shared/menuitens' %>
				<% elsif admin_signed_in?%>
				<%= render 'shared/menuitens_admin' %>
				<% else %>
				<li class="area_professor">
					<%= link_to 'Área do Professor', new_teacher_session_path %>
				</li>
				<% end %>

			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>

app/views/shared/_notification.html.erb
<h2>Enviar dica</h2>

<%= form_tag('/send_notification') do %>
  <div class="field">
    <%= text_area_tag(:message, nil, cols: "40", rows: "5") %>
  </div>
  <br>
  <div class="actions">
    <%= submit_tag 'Enviar notificação', class: "btn btn-primary" %>
  </div>
<% end %>

<br>