config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'

  devise_for :admins, path: "admin", 
    controllers: { sessions: "admin/sessions", registrations: 'admin/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
  end
  
  devise_for :teachers, path: "teachers", 
    controllers: { sessions: "teachers/sessions", registrations: 'teachers/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
  end
  
  scope :admin do
    resources :tips
    get      'teachers'                        , to: 'admin/teachers#index', as: :admin_teachers_index
    get      'teachers/new'                    , to: 'admin/teachers#new', as: :admin_teachers_new
    post     'teachers'                        , to: 'admin/teachers#create', as: :admin_teachers_create
    
    #resources :teachers, :controller => "admin/teachers"
  end
  resources :teachers do
    resources :lessons
  end
  
  patch 'teachers/avatarupload' => 'teachers#avatarupload', as: :teacher_avatar_upload
  
  get 'invalid' => 'landing#invalid', as: :invalid
  get 'mailtest' => 'landing#mailtest', as: :mailtest
  
  get 'settings' => 'teachers#settings', as: :settings

  post 'save_settings' => 'teachers#save_settings', as: :save_settings

  devise_for :users
  resources :users

  namespace :api, constraints: { format: 'json' } do  
    devise_for :users, controllers: {sessions: "api/sessions", registrations: "api/registrations", passowords: "api/passwords"}

    resources :tips, only: [:index]

    post 'users/:id/lessons/remove_reserves.json' => 'reserves#removemany', as: :removereserves

    get     'order/:order_id/verify'                        , to: 'orders#verify', as: :orders_verify
    post    ':user_id/mailtest'                             , to: 'orders#mailtest'
    post    'order/:order_id/pay'                           , to: 'orders#pay',            as: :pay
    get     'confirmation'                                  , to: 'orders#confirmation',   as: :confirmation
    post    'notify'                                        , to: 'orders#notify',   as: :pay_notify

    post    'avatar_upload'                                 , to: 'users#avatar_upload'
    post    'order'                                         , to: 'orders#create'
    
    resources :users do
      get '' => 'users#index', as: :user_index
      get 'reserves' => 'reserves#index', as: :reserves_index
      # /api/users/:user_id/lessons/:lesson_id/reserves
      resources :lessons do
        resources :reserves
      end
      member do  
        get '' => 'users#show', as: :user 
        put 'edit' => 'users#edit', as: :user_edit
      end
    end
    
    post 'users/:id/lessons/reserves.json' => 'reserves#createmany', as: :createreserves
    
    post 'reservelessons/rate' => 'reserves#rate', as: :reserves_rate

    get 'teachers/:id/lessons' => 'lessons#index', as: :teachers_lesson
    get 'teachers/:id' => 'teachers#show', as: :teacher
    get 'teachers' => 'teachers#index', as: :teacher_index
    # get 'search' => 'lessons#search', as: :lesson_search
    
    get 'languages' => 'lists#languages', as: :languages_list
    get 'levels' => 'lists#levels', as: :levels_list
    get 'schedules' => 'lists#schedules', as: :schedules_list
    get 'platforms' => 'lists#platforms', as: :platforms_list
    get 'search' => 'teachers#search', as: :teacher_search

    # get  'reserves' => 'users#index', as: :reserve_index
    # get  'reserves/:id' => 'users#show', as: :reserve
    # post 'reserves' => 'users#new', as: :reserve_new
    
  end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_attached_file :avatar, styles: { :mobile => "300x300>" }, :default_url => "#{WEE_CONFIG['ROOT_URL']}/assets/avatar/small/missing.png"
  validates_attachment_content_type :avatar, :content_type => /^image\/(png|gif|jpeg|jpg)/
  
  attr_accessor :teacher_lessons
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # has_many :levels, through: :teacher_languages
  
  has_many :teacher_languages
  has_many :languages, through: :teacher_languages

  # has_many :levels, through: :languages

  has_many :teacher_schedules
  has_many :schedules, through: :teacher_schedules

  has_many :lessons
  
  has_many :reservelessons, through: :lessons
  
  def avatarurl
    avatarurl = self.avatar.url(:mobile)

    if avatarurl.blank?
      return ""
    end
    return avatarurl
  end

  def self.search(skype = nil, hangout = nil, level = nil, language = nil, schedule = nil, page = 1, per_page = 10)
    teachers = Teacher
                .joins(:lessons)
                .where("(lessons.id NOT IN (SELECT reservelessons.lesson_id FROM reservelessons where reservelessons.deleted_at IS  NULL))")
                .where("lessons.date > ? ", DateTime.now)
            
    language_join = false    
    if not language.nil? and not language.blank? then
      language_join = true
      teachers = teachers.joins(:teacher_languages).where("teacher_languages.language_id = ?", language)
    end

    if not level.nil? and not level.blank? then
      if not language_join then
        teachers = teachers.joins(:teacher_languages)
      end
      teachers = teachers.joins(:teacher_languages => :language_levels).where("language_levels.level_id = ?", level)
    end
    
    if not skype.nil? and not skype.blank? then
      teachers = teachers.where("skype is not null and skype != ? ", "")
    end  
    if not hangout.nil? and not hangout.blank? then
      teachers = teachers.where("hangout is not null and hangout != ? ", "")
    end
    
    if not schedule.nil? and not schedule.blank? then
      teachers = teachers.where("lessons.period in (?) ", schedule.split(","))
    end
    
    return teachers.distinct.paginate(:page => page, :per_page => per_page)

  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < ApplicationController
    

    
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  respond_to :html

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all.order(name: :asc)
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    pwd = SecureRandom.hex(4)
    params[:teacher][:password] = pwd
    params[:teacher]["password_confirmation"] = pwd
    
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        #envia email com a senha
        TeacherMailer.welcome_email(@teacher, pwd).deliver
        format.html { redirect_to admin_teachers_index_path, :flash => { :success => "Professor cadastrado com sucesso." } }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      # @teacher = Teacher.find(params[:id])
      @teacher = current_teacher
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :email, :password, "password_confirmation")
    end
end

app/controllers/api/teachers_controller.rb
require 'ServiceColumns'

class Api::TeachersController < ApplicationController
  respond_to :json
  before_action :set_user, only: [:show]
  
  #before_filter :authenticate_user_from_token!

  # GET /api/teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /api/teachers/1.json
  def show
    return render :status => 200, :json => @teacher.as_json(ServiceColumns.teachers)
  end

  def search
    page = params[:page] || 1
    per_page = params[:per_page] || 1

    skype = params[:skype]
    hangout = params[:hangout]
    level = params[:level]
    language = params[:language]
    schedule = params[:schedule]

    @teachers = Teacher.search(skype, hangout, level, language, schedule, page, per_page)
    @total = {:page => page.to_i, :total => (@teachers.count / per_page.to_f).round }

    return render :status => 200, :json => {:teachers => @teachers.as_json(ServiceColumns.teachers), :pagination => @total}
  end

  private

    def set_user
      @teacher = Teacher.find(params[:id])
    end
  
  # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name)
    end

end

app/controllers/teachers/registrations_controller.rb
class Teachers::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  
  #force_ssl only: [:new,:create]
  
  skip_before_filter  :verify_authenticity_token

  def edit
    #flash.clear
    super    
  end
  
  def new
    flash.clear
    super
  end
  
=begin
  # POST /resource
  def create
    pwd = SecureRandom.hex(8)
    params[:dentist][:password] = pwd
    params[:dentist]["password_confirmation"] = pwd

    build_resource(sign_up_params) 
    flash.clear
    
    if params["accept_termos"].nil? or params["accept_termos"] != "on" then
      flash["alert alert-danger"] = I18n.t(:error_termos_de_uso_nao_aceito)
      render "new"
    else
      super
      if resource.errors.nil? or resource.errors.empty? then
        value = Dentistas::PaymentHelpers::get_value(resource.plano)
        payment(resource, value, params)
        Thread.new do
          payment = Payment.where(:dentist_id => resource.id).last
          DentistaMailer.payment_process(resource, payment).deliver!
        end
        sign_out
      else
        #erro cadastro não realizado
      end
     end
  end

  def edit
    @dentista = current_dentist
    build_dentista(@dentista)
    super
    flash.clear  
    
  end

  def build_dentista(dentista)
      if dentista.address.nil? then
        dentista.address = Address.new
      end
      if dentista.promocao.nil? then
        dentista.promocao = Promocao.new
      end
      if dentista.at_normal.nil? or dentista.at_normal.size <= 0  then
        dentista.at_normal.build
      end
    
      if dentista.at_emerg.nil? or dentista.at_emerg.size <= 0  then
        dentista.at_emerg.build
      end
    end


  def dentista_params
    params.require(:dentist).permit(:_id, :nome, :site, :email, :profile, :icon, :destaque, :phones => [], :equipe => [], :servicos => [],
    address: [:street, :number, :complement, :neighborhood, :zip_code, :city, :state], promocao: [:perc, :servico], at_normal: [:dia_sem, :h_open, :h_close], at_emerg: [:dia_sem, :h_open, :h_close])
  end
  

  
  def sign_up_params
    params.require(:dentist).permit(:nome, :email, :plano, :password, :password_confirmation, :phones => [])
  end
=end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_update_path_for(resource)
    edit_teacher_registration_path(resource)
  end
  
  def update
    super
=begin
    @teacher = current_teacher
    
    params_update = teachers_params

    if params_update[:password].nil? or params_update[:password].blank? then
      params_update[:password] = nil
      params_update[:password_confirmation] = nil
      params_update.delete :password
      params_update.delete :password_confirmation
    end
    
    puts ">>>>>> #{params_update}"
    if @teacher.update(params_update)
      flash["alert alert-success"] = "Alteração efetuada com sucesso."
      
    else
      #set_error(@teacher, "Ocorreu algum erro.")
    end

    
    render 'edit'
=end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :skype
    devise_parameter_sanitizer.for(:account_update) << :hangout
    devise_parameter_sanitizer.for(:account_update) << :accepted_term    
    devise_parameter_sanitizer.for(:account_update) << :cpf
    devise_parameter_sanitizer.for(:account_update) << :street
    devise_parameter_sanitizer.for(:account_update) << :number
    devise_parameter_sanitizer.for(:account_update) << :state
    devise_parameter_sanitizer.for(:account_update) << :city
    devise_parameter_sanitizer.for(:account_update) << :neighborhood
    devise_parameter_sanitizer.for(:account_update) << :complement
    devise_parameter_sanitizer.for(:account_update) << :zip_code
    devise_parameter_sanitizer.for(:account_update) << :phone
    
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
  def teachers_params
    params.require(:teacher).permit(:id, :name, :email, :password, :password_confirmation)
  end
  
end

app/controllers/teachers/sessions_controller.rb
class Teachers::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
  #before_filter :sign_out_pre_login, only: [:new]

  def after_sign_up_path_for(resource)
    root_path(:msg => "Cadastro efetuado")
  end
  
  def after_sign_in_path_for(resource)
    root_path(:msg => "Login efetuado")
  end
  
  def sign_out_pre_login
    sign_out(current_teacher)
    sign_out(current_admin)
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper

  def find(id)
    @language_ids.each{|l| 
      if l.keys.include?(id) == true
        return true
      end
    }
    return false
  end

  def get_lang(id)
    @language_ids.each{|l| 
      if l.keys.include?(id) == true
        return l
      end
    }
    return nil
  end

end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
<% if @teacher.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

	<ul>
		<% @teacher.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<%= render 'shared/navigation_bar'%>

<div class="container">
  <div class= "top-buffer">
    <div class="col-md-offset-2">

      <h1>Listing Teachers</h1>
      <p id="notice"><%= notice %></p>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @teachers.each do |teacher| %>
            <tr>
              <td><%= teacher.name %></td>
              <td><%= link_to 'Show', teacher %></td>
              <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
              <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Teacher', new_teacher_path %>
    </div>
  </div>
</div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/newlanguage.html.erb
<%= render 'shared/navigation_bar'%>

<div class="container">
  <div class= "top-buffer">
    <div class="col-md-offset-1">
    
    <h2> Disponibilizar horário </h2>

    <%= form_for([@teacher, @lesson]) do |f| %>
        <%= f.hidden_field :teacher_id, :value => @teacher.id %>
      <div class="field">
        <%= f.label :Data %>
        <%= f.date_field :date, :required => true %>
      
        <%= f.label :Horário %>
        <%= time_field_tag :time, :required => true %>
      </div>
      
<!--       <div class="field">
        <%= f.label :Idioma %>
        <%= f.collection_select :language_id, @languages, :id, :name %>
      
        <%= f.label :Nível %>
        <%= f.collection_select :level_id, @levels, :id, :name %>
      </div>
 -->      <p/>
      <div class="actions">
        <%= f.submit, :class=> "btn btn-primary" %>
      </div>

    <% end %>
  </div>
</div>

app/views/teachers/notification.html.erb
<%= render 'shared/navigation_bar'%>

<%= render 'shared/notification' %>

app/views/teachers/settings.html.erb
<%= render 'shared/navigation_bar'%>

<div class="container">
	<div class= "top-buffer">
		<div class="col-md-offset-1">

			<% flash.each do |name, msg| -%>
			<%= content_tag :div, msg, class: "alert alert-#{name} alert-block" %>
			<% end %>
			<div class="row">

				<div class="col-md-8 col-md-offset-2">
					<div class="panel-default">

						<h1>Meus Idiomas</h1>

						<%= form_for :save_settings, :url =>{:controller => :teachers, :action => :save_settings} do |f| %>

						<div class="form-group">

							<%= label_tag 'Selecione os idiomas que ensina:' %>
							<br>

							<% @languages.each do |language| %>
							<div class="panel panel-default">
								<div class="panel-body">
									<h4> <%= h language.name %></h4>
									<br>

									<% @levels.each do |level| %>

									<%= check_box_tag "language_ids[#{language.id}][#{level.id}]", level.id, get_lang(language.id).present? ? get_lang(language.id).values[0].include?(level.id) : false %>
									<label class="label-level"><%= h level.name %> </label>
									<% end %>
									<br>

								</div>
							</div>

							<% end %>

						</div>
						<div  class="form-group">
							<%= submit_tag 'Salvar', class: "btn btn-primary center-block"%>
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>