config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'

  devise_for :admins, path: "admin", 
    controllers: { sessions: "admin/sessions", registrations: 'admin/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
  end
  
  devise_for :teachers, path: "teachers", 
    controllers: { sessions: "teachers/sessions", registrations: 'teachers/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
  end
  
  scope :admin do
    resources :tips
    get      'teachers'                        , to: 'admin/teachers#index', as: :admin_teachers_index
    get      'teachers/new'                    , to: 'admin/teachers#new', as: :admin_teachers_new
    post     'teachers'                        , to: 'admin/teachers#create', as: :admin_teachers_create
    
    #resources :teachers, :controller => "admin/teachers"
  end
  resources :teachers do
    resources :lessons
  end
  
  patch 'teachers/avatarupload' => 'teachers#avatarupload', as: :teacher_avatar_upload
  
  get 'invalid' => 'landing#invalid', as: :invalid
  get 'mailtest' => 'landing#mailtest', as: :mailtest
  
  get 'settings' => 'teachers#settings', as: :settings

  post 'save_settings' => 'teachers#save_settings', as: :save_settings

  devise_for :users
  resources :users

  namespace :api, constraints: { format: 'json' } do  
    devise_for :users, controllers: {sessions: "api/sessions", registrations: "api/registrations", passowords: "api/passwords"}

    resources :tips, only: [:index]

    post 'users/:id/lessons/remove_reserves.json' => 'reserves#removemany', as: :removereserves

    get     'order/:order_id/verify'                        , to: 'orders#verify', as: :orders_verify
    post    ':user_id/mailtest'                             , to: 'orders#mailtest'
    post    'order/:order_id/pay'                           , to: 'orders#pay',            as: :pay
    get     'confirmation'                                  , to: 'orders#confirmation',   as: :confirmation
    post    'notify'                                        , to: 'orders#notify',   as: :pay_notify

    post    'avatar_upload'                                 , to: 'users#avatar_upload'
    post    'order'                                         , to: 'orders#create'
    
    resources :users do
      get '' => 'users#index', as: :user_index
      get 'reserves' => 'reserves#index', as: :reserves_index
      # /api/users/:user_id/lessons/:lesson_id/reserves
      resources :lessons do
        resources :reserves
      end
      member do  
        get '' => 'users#show', as: :user 
        put 'edit' => 'users#edit', as: :user_edit
      end
    end
    
    post 'users/:id/lessons/reserves.json' => 'reserves#createmany', as: :createreserves
    
    post 'reservelessons/rate' => 'reserves#rate', as: :reserves_rate

    get 'teachers/:id/lessons' => 'lessons#index', as: :teachers_lesson
    get 'teachers/:id' => 'teachers#show', as: :teacher
    get 'teachers' => 'teachers#index', as: :teacher_index
    # get 'search' => 'lessons#search', as: :lesson_search
    
    get 'languages' => 'lists#languages', as: :languages_list
    get 'levels' => 'lists#levels', as: :levels_list
    get 'schedules' => 'lists#schedules', as: :schedules_list
    get 'platforms' => 'lists#platforms', as: :platforms_list
    get 'search' => 'teachers#search', as: :teacher_search

    # get  'reserves' => 'users#index', as: :reserve_index
    # get  'reserves/:id' => 'users#show', as: :reserve
    # post 'reserves' => 'users#new', as: :reserve_new
    
  end
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  validates :description, length: { minimum: 8, maximum: 250 }
end

app/controllers/api/tips_controller.rb
require 'ServiceColumns'

class Api::TipsController < ApplicationController
  respond_to :json
  before_filter :authenticate_user_from_token!

  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 1

    @tips = Tip.all.order(created_at: :desc).paginate(:page => page.to_i, :per_page => per_page.to_i)

    @total = {:page => page.to_i, :total => (@tips.count / per_page.to_f).round }
  
    return render :status => 200, :json => {:tips => @tips, :pagination => @total}
  end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all.order(created_at: :desc)
  end

  # GET /admin/admin/tips/1
  # GET /admin/admin/tips/1.json
  def show
  end

  # GET /admin/admin/tips/new
  def new
    @tip = Tip.new
  end

  # GET /admin/admin/tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        send_notification(@tip.description)
        format.html { redirect_to tips_path, :flash => { :success => "Dica inserida com sucesso." } }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def send_notification(message)
    require 'parse-ruby-client'

    client = Parse.create(
      :application_id => WEE_CONFIG['PARSE_APP_ID'], 
      :api_key        => WEE_CONFIG['PARSE_API_KEY'], 
      :quiet      => false)

    data = { :alert =>message, :screen => WEE_CONFIG['SCREEN_ANDROID_TIPS'] }
    push = client.push(data)
    push.save
  end

  # PATCH/PUT /admin/tips/1
  # PATCH/PUT /admin/tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to tips_path, :flash => { :success => "Dica alterada com sucesso." } }
        format.json { render :show, status: :ok, location: @tip, :flash => { :success => "Dica alterada com sucesso." } }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/admin/tips/1
  # DELETE /admin/admin/tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, :flash => { :success => "Dica deletada com sucesso." } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:description)
    end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">

      <ul>
      <% @tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area(:description, :class=>"form-control", rows: "10") %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Salvar", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<%= render 'shared/navigation_bar'%>


<div class="container">
  <div class= "top-buffer">
    <div class="col-md-offset-1">
      <h1>Editar Dica</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tips/index.html.erb
<%= render 'shared/navigation_bar'%>

<div class="container">
	<div class= "top-buffer">
		<div class="col-md-offset-1">

			<% flash.each do |name, msg| -%>
				<%= content_tag :div, msg, class: "alert alert-#{name} alert-block" %>
			<% end %>
		<div class="row">

			<div class="col-md-8 col-md-offset-2">
				
			<div class="panel-default">

				<h1>Dicas</h1>

				<table id="admin_tips" class="table table-striped">
					<thead>
						<tr>
							<td>ID</td>
							<td>Dica</td>
							<td class="no-sort"></td>
							<td></td>
						</tr>
					</thead>

					<tbody class='table-hover'>

						<% @tips.each do |tip| %>
						<tr>
							<td><%= tip.id%></td>
							<td><%= tip.description %></td>
							<td width="10%"><%= link_to 'Editar', edit_tip_path(tip) %></td>
							<td width="10%"><%= link_to 'Apagar', tip, method: :delete, data: { confirm: 'Deseja apagar esta dica?' } %></td>
						</tr>
						<% end %>
					</tbody>
				</table>

				<%= link_to 'Nova dica', new_tip_path, class: "btn btn-primary" %>
			</div>
		</div>
	</div>
</div>	</div>
</div>

app/views/tips/new.html.erb
<%= render 'shared/navigation_bar'%>
<div class="container">
  <div class= "top-buffer">
    <div class="col-md-offset-1">

      <h1>Nova Dica</h1>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/tips/show.html.erb
<%= render 'shared/navigation_bar'%>

<p id="notice"><%= notice %></p>
<div class="container">
  <div class= "top-buffer">
    <div class="col-md-offset-1">

      <p>
        <strong>Dica:</strong>
        <%= @tip.description %>
      </p>

      <%= link_to 'Editar', edit_tip_path(@tip) %> |
      <%= link_to 'Voltar', tips_path %>
    </div>
  </div>
</div>